# Generated by Django 4.0 on 2021-12-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('SW', 'Sweater')], max_length=2),
        ),
    ]
